#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Run ctest and upload the JUnit test results as an artifact.
#-----------------------------------------------------------------------------#

name: "Run ctest"
description: "Run ctest with a preset and upload test-output as an artifact"
inputs:
  preset:
    description: "ctest preset name"
    required: false
    default: "base"
  name:
    description: "Suffix for the uploaded test-results artifact"
    required: true
  strict:
    description: "Enable exact comparisons in unit tests (Test::strict_testing)"
    required: false
    default: "false"
  split-app:
    description: "Test {preset}-unit and {preset}-app separately"
    required: false
    default: "false"
  filter-unit:
    description: "Run only unit tests that match this regex, or 'none' to skip"
    required: false
    default: ""
outputs:
  outcome:
    description: "Outcome of the ctest step ('success' or 'failure')"
    value: ${{steps.all.outcome || (steps.unit.outcome && steps.app.outcome)}}

runs:
  using: "composite"
  steps:
    - name: Run unit tests
      id: unit
      if: ${{ inputs.split-app && inputs.filter-unit != "none"}}
      shell: bash
      run: |
        ctest --preset=${{inputs.preset}}-unit \
          ${{inputs.filter-unit && format('-R "{0}", inputs.filter-unit) || ''}}
    - name: Run app tests
      id: app
      if: ${{ !cancelled() && inputs.split-app }}
      shell: bash
      run: ctest --preset=${{inputs.preset}}-app
    - name: Run all tests
      id: all
      if: ${{ !inputs.split-app }}
      shell: bash
      run: ctest --preset=${{inputs.preset}}
    - name: Upload test results for pull_request_completed
      uses: actions/upload-artifact@v7
      if: ${{ always() }}
      with:
        # NOTE: these must be compatible with pull_request_completed.yml
        name: test-results-${{inputs.name}}
        path: "test-output/**/*.xml"
        if-no-files-found: error
        retention-days: 1
