spack:
  specs:
  - cmake
  - cuda
  - geant4
  - git

  - googletest

  - hepmc3
  - ninja
  - nlohmann-json
  - openmpi
  - python

  - root
  - swig

  - veccore
  - vecgeom +gdml
  concretization: together
  packages:
    cuda:
      buildable: false
      externals:
      - spec: cuda@11.1.0
        prefix: /usr/local/cuda
    root:
      variants: ~davix ~examples ~x ~opengl ~tbb ~rootfit ~python ~math ~gsl cxxstd=14
    all:
      target:
      - x86_64
      variants: +cuda cuda_arch=70 cxxstd=14
      providers:
        blas:
        - openblas
        lapack:
        - openblas
        mpi:
        - openmpi
  config:
    install_tree: /opt/software
  view: /opt/view
