spack:
  specs:
    - cmake
    - "geant4@11.0"
    - git
    - "googletest@1.10:"
    - hepmc3
    - mpi
    - ninja
    - nlohmann-json
    - "python@3.6:"
    - "root@6.28: cxxstd=17"
    - "swig@4.1:"
    - "vecgeom@1.2.4: +gdml cxxstd=17"
  concretizer:
    unify: true
  packages:
    cuda:
      buildable: false
      externals:
      - spec: cuda@12.4.1
        prefix: /usr/local/cuda
    root:
      variants: ~davix ~examples ~x ~opengl ~tbb ~rootfit ~python ~math ~gsl cxxstd=17
    all:
      target:
      - x86_64_v3
      variants: +cuda cuda_arch=70 cxxstd=17
      providers:
        blas:
        - openblas
        lapack:
        - openblas
        mpi:
        - openmpi
  config:
    install_tree: /opt/software
  view: /opt/view
