title: Celeritas documentation
description: User and developer documentation for the Celeritas code
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
include:
- _includes
- _layouts
- _sources
- _static
