title: "Celeritas: accelerated High Energy Physics Monte Carlo simulation"
description: >-
  User and developer documentation for the Celeritas code
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: true
logo: _includes/full-logo.png
plugins:
- jekyll-remote-theme
include:
- _includes
- _layouts
- _sources
- _static
