classDiagram
  Object <|-- Transformed
  Object <|-- Shape
  Object <|-- NegatedObject
  Object <|-- JoinObjects
  ShapeBase <|-- Shape
  class Object {
    +string_view label()*
    +NodeId build(VolumeBuilder&)*
  }
  <<Interface>> Object
  class Transformed {
    -SPConstObject obj
    -VariantTransform transform
  }
  Transformed *-- Object

  class ShapeBase {
    #IntersectRegion const& interior()*
  }
  <<Abstract>> ShapeBase

  class Shape {
    -string label;
    -IntersectRegion region;
  }
  Shape *-- IntersectRegion

  class IntersectRegion {
    +void build(IntersectSurfaceBuilder&)*
  }
  <<Interface>> IntersectRegion
  IntersectRegion <|-- Box
  IntersectRegion <|-- Sphere

  class Box {
    -Real3 halfwidths
  }
  class Sphere {
    -real_type radius
  }

  Shape <|.. BoxShape
  Shape <|.. SphereShape

  BoxShape *-- Box
  SphereShape *-- Sphere
