//----------------------------------*-C++-*----------------------------------//
// Copyright 2024 UT-Battelle, LLC, and other Celeritas developers.
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: (Apache-2.0 OR MIT)
//---------------------------------------------------------------------------//
//! \file celeritas/optical/ScintillationPreGenerator.hh
//---------------------------------------------------------------------------//
#pragma once

#include "corecel/Assert.hh"
#include "corecel/Macros.hh"
#include "corecel/data/StackAllocator.hh"
#include "celeritas/Quantities.hh"
#include "celeritas/phys/ParticleTrackView.hh"
#include "celeritas/random/distribution/NormalDistribution.hh"
#include "celeritas/random/distribution/PoissonDistribution.hh"
#include "celeritas/track/SimTrackView.hh"

#include "OpticalDistributionData.hh"
#include "OpticalGenData.hh"
#include "OpticalPropertyData.hh"
#include "ScintillationData.hh"

namespace celeritas
{
//---------------------------------------------------------------------------//
/*!
 * Sample the number of Scintillation photons to be generated by
 * \c ScintillationGenerator and populate \c OpticalDistributionData values
 * using Param and State data.
 */
class ScintillationPreGenerator
{
  public:
    //!@{
    //! \name Type aliases
    using DistributionAllocator = StackAllocator<OpticalDistributionData>;
    //!@}

    // Construct with optical properties, scintillation, and step data
    inline CELER_FUNCTION
    ScintillationPreGenerator(ParticleTrackView const& particle,
                              SimTrackView const& sim,
                              Real3 const& pos,
                              OpticalMaterialId mat_id,
                              units::MevEnergy energy_deposition,
                              NativeCRef<ScintillationData> const& shared,
                              OpticalPreStepData const& step_data,
                              DistributionAllocator& allocate);

    // Populate optical distribution data for the Scintillation Generator
    template<class Generator>
    inline CELER_FUNCTION size_type operator()(Generator& rng);

  private:
    units::ElementaryCharge charge_;
    real_type step_len_;
    real_type time_;
    OpticalMaterialId mat_id_;
    NativeCRef<ScintillationData> const& shared_;
    EnumArray<StepPoint, OpticalStepData> points_;
    DistributionAllocator& allocate_;
    real_type mean_num_photons_;
};

//---------------------------------------------------------------------------//
// INLINE DEFINITIONS
//---------------------------------------------------------------------------//
/*!
 * Construct with input parameters.
 */
CELER_FUNCTION ScintillationPreGenerator::ScintillationPreGenerator(
    ParticleTrackView const& particle,
    SimTrackView const& sim,
    Real3 const& pos,
    OpticalMaterialId mat_id,
    units::MevEnergy energy_deposition,
    NativeCRef<ScintillationData> const& shared,
    OpticalPreStepData const& step_data,
    DistributionAllocator& allocate)
    : charge_(particle.charge())
    , step_len_(sim.step_length())
    , time_(step_data.time)
    , mat_id_(mat_id)
    , shared_(shared)
    , allocate_(allocate)
{
    CELER_EXPECT(step_len_ > 0);
    CELER_EXPECT(mat_id_);
    CELER_EXPECT(shared_);
    CELER_EXPECT(step_data);

    points_[StepPoint::pre].speed = step_data.speed;
    points_[StepPoint::pre].pos = step_data.pos;
    points_[StepPoint::post].speed = particle.speed();
    points_[StepPoint::post].pos = pos;

    if (shared_.scintillation_by_particle())
    {
        // TODO: implement sampling for particles, assert particle data, and
        // cache mean number of photons
        CELER_ASSERT_UNREACHABLE();
    }
    else
    {
        // Scintillation will be performed on materials only
        CELER_ASSERT(mat_id_ < shared_.materials.size());
        auto const& material = shared_.materials[mat_id_];

        // TODO: Use visible energy deposition when Birks law is implemented
        mean_num_photons_ = material ? material.yield_per_energy
                                           * energy_deposition.value()
                                     : 0;
    }
}

//---------------------------------------------------------------------------//
/*!
 * Sample number of photons to generate and create optical distribution data.
 *
 * Returns the number of photons.
 */
template<class Generator>
CELER_FUNCTION size_type ScintillationPreGenerator::operator()(Generator& rng)
{
    if (mean_num_photons_ == 0)
    {
        return 0;
    }

    // Material-only sampling
    // TODO: handle failure to allocate space?
    OpticalDistributionData* data = allocate_(1);
    CELER_ASSERT(data);
    if (mean_num_photons_ > 10)
    {
        real_type sigma = shared_.resolution_scale[mat_id_]
                          * std::sqrt(mean_num_photons_);
        data->num_photons = clamp_to_nonneg(
            NormalDistribution<real_type>(mean_num_photons_, sigma)(rng)
            + real_type{0.5});
    }
    else
    {
        data->num_photons
            = PoissonDistribution<real_type>(mean_num_photons_)(rng);
    }

    if (data->num_photons > 0)
    {
        // Assign remaining data
        data->time = time_;
        data->step_length = step_len_;
        data->charge = charge_;
        data->material = mat_id_;
        data->points = points_;
    }
    return data->num_photons;
}

//---------------------------------------------------------------------------//
}  // namespace celeritas
