//------------------------------- -*- C++ -*- -------------------------------//
// Copyright Celeritas contributors: see top-level COPYRIGHT file for details
// SPDX-License-Identifier: (Apache-2.0 OR MIT)
//---------------------------------------------------------------------------//
//! \file celeritas/mucf/interactor/DTMucfInteractor.hh
//---------------------------------------------------------------------------//
#pragma once

#include "corecel/Macros.hh"
#include "corecel/data/StackAllocator.hh"
#include "corecel/math/ArrayUtils.hh"
#include "corecel/random/distribution/GenerateCanonical.hh"
#include "corecel/random/distribution/IsotropicDistribution.hh"
#include "celeritas/grid/NonuniformGridCalculator.hh"
#include "celeritas/mucf/data/DTMixMucfData.hh"
#include "celeritas/phys/Interaction.hh"
#include "celeritas/phys/Secondary.hh"

namespace celeritas
{
//---------------------------------------------------------------------------//
/*!
 * Muon-catalyzed fusion of \f$ (dt)_\mu \f$ molecules.
 *
 * Fusion channels:
 * - \f$ \alpha + \mu + n \f$
 * - \f$ (\alpha)_\mu + n \f$
 */
class DTMucfInteractor
{
  public:
    enum class Channel
    {
        alpha_muon_neutron,  //!< \f$ \alpha + \mu + n \f$
        muonicalpha_neutron,  //!< \f$ (\alpha)_\mu + n \f$
        size_
    };

    // Construct from shared and state data
    inline CELER_FUNCTION
    DTMucfInteractor(NativeCRef<DTMixMucfData> const& data,
                     Channel channel,
                     StackAllocator<Secondary>& allocate);

    // Sample an interaction with the given RNG
    template<class Engine>
    inline CELER_FUNCTION Interaction operator()(Engine& rng);

  private:
    // Shared constant physics properties
    NativeCRef<DTMixMucfData> const& data_;
    // Selected fusion channel
    Channel channel_{Channel::size_};
    // Allocate space for secondary particles
    StackAllocator<Secondary>& allocate_;

    // Number of secondaries per channel
    EnumArray<Channel, size_type> num_secondaries_{
        3,  // alpha_muon_neutron
        2  // muonicalpha_neutron
    };

    // Total energy generated by the dt fusion reaction
    inline CELER_FUNCTION units::MevEnergy total_fusion_energy() const
    {
        return units::MevEnergy{17.6};
    }

    // Neutron kinetic energy
    inline CELER_FUNCTION units::MevEnergy neutron_kinetic_energy() const
    {
        return units::MevEnergy{14.1};
    }

    // Calculate momentum magnitude from energy and mass
    inline CELER_FUNCTION real_type calc_momentum(units::MevEnergy energy,
                                                  units::MevMass mass) const;
};

//---------------------------------------------------------------------------//
// INLINE DEFINITIONS
//---------------------------------------------------------------------------//
/*!
 * Construct with shared and state data.
 */
CELER_FUNCTION
DTMucfInteractor::DTMucfInteractor(NativeCRef<DTMixMucfData> const& data,
                                   Channel const channel,
                                   StackAllocator<Secondary>& allocate)
    : data_(data), channel_(channel), allocate_(allocate)
{
    CELER_EXPECT(data_);
    CELER_EXPECT(channel_ < Channel::size_);
}

//---------------------------------------------------------------------------//
/*!
 * Sample a dt muonic molecule fusion.
 *
 * \note Since secondaries come from an at rest interaction, their final state
 * is a simple combination of random direction + momentum conservation.
 */
template<class Engine>
CELER_FUNCTION Interaction DTMucfInteractor::operator()(Engine& rng)
{
    // Allocate space for the final fusion channel
    Secondary* secondaries = allocate_(num_secondaries_[channel_]);
    if (secondaries == nullptr)
    {
        // Failed to allocate space for secondaries
        return Interaction::from_failure();
    }

    IsotropicDistribution sample_isotropic;
    NonuniformGridCalculator sample_muon_energy(data_.muon_energy_cdf,
                                                data_.reals);

    // Neutron is the same on both cases: 14.1 MeV with random direction
    secondaries[0].particle_id = data_.particle_ids.neutron;
    secondaries[0].energy = this->neutron_kinetic_energy();
    secondaries[0].direction = sample_isotropic(rng);

    switch (channel_)
    {
        case Channel::alpha_muon_neutron: {
            // Muon: Final state sampled from CDF
            secondaries[1].particle_id = data_.particle_ids.mu_minus;
            secondaries[1].direction = sample_isotropic(rng);
            secondaries[1].energy = units::MevEnergy{
                sample_muon_energy(generate_canonical(rng))};

            // Alpha: Final state calculated via energy/momentum conservation:
            // E_alpha = E_total - E_neutron - E_muon
            // p_alpha = - (p_neutron + p_muon)
            auto const neutron_momentum_mag = this->calc_momentum(
                secondaries[0].energy, data_.particle_masses.neutron);
            auto const muon_momentum_mag = this->calc_momentum(
                secondaries[1].energy, data_.particle_masses.mu_minus);
            Real3 alpha_momentum_vec;
            for (auto i : range(3))
            {
                alpha_momentum_vec[i]
                    = -(secondaries[0].direction[i] * neutron_momentum_mag
                        + secondaries[1].direction[i] * muon_momentum_mag);
            }

            secondaries[2].particle_id = data_.particle_ids.alpha;
            secondaries[2].direction = make_unit_vector(alpha_momentum_vec);
            secondaries[2].energy = this->total_fusion_energy()
                                    - secondaries[0].energy
                                    - secondaries[1].energy;
            break;
        }

        case Channel::muonicalpha_neutron: {
            // Muonic alpha: Equal and opposite momentum to neutron
            secondaries[1].particle_id = data_.particle_ids.muonic_alpha;
            secondaries[1].energy = secondaries[0].energy;
            for (auto i : range(3))
            {
                secondaries[1].direction[i] = -secondaries[0].direction[i];
            }
            break;
        }

        default:
            CELER_ASSERT_UNREACHABLE();
    }

    // Kill primary and generate secondaries
    Interaction result = Interaction::from_absorption();
    result.secondaries = {secondaries, num_secondaries_[channel_]};
    return result;
}

//---------------------------------------------------------------------------//
/*!
 * Calculate momentum magnitude from particle energy and mass.
 */
CELER_FUNCTION real_type DTMucfInteractor::calc_momentum(
    units::MevEnergy energy, units::MevMass mass) const

{
    return std::sqrt(ipow<2>(value_as<units::MevEnergy>(energy))
                     + 2 * value_as<units::MevMass>(mass)
                           * value_as<units::MevEnergy>(energy));
}

//---------------------------------------------------------------------------//
}  // namespace celeritas
