//------------------------------- -*- C++ -*- -------------------------------//
// Copyright Celeritas contributors: see top-level COPYRIGHT file for details
// SPDX-License-Identifier: (Apache-2.0 OR MIT)
//---------------------------------------------------------------------------//
//! \file celeritas/mucf/interactor/DTMucfInteractor.hh
//---------------------------------------------------------------------------//
#pragma once

#include "corecel/Macros.hh"
#include "corecel/data/StackAllocator.hh"
#include "corecel/math/ArrayUtils.hh"
#include "corecel/random/distribution/GenerateCanonical.hh"
#include "corecel/random/distribution/IsotropicDistribution.hh"
#include "celeritas/grid/NonuniformGridCalculator.hh"
#include "celeritas/mucf/data/DTMixMucfData.hh"
#include "celeritas/phys/Interaction.hh"
#include "celeritas/phys/Secondary.hh"

namespace celeritas
{
//---------------------------------------------------------------------------//
/*!
 * Muon-catalyzed fusion of \f$ (dt)_\mu \f$ molecules.
 *
 * Fusion channels:
 * - \f$ \alpha + \mu + n \f$
 * - \f$ (\alpha)_\mu + n \f$
 */
class DTMucfInteractor
{
  public:
    enum class Channel
    {
        alpha_muon_neutron,  //!< \f$ \alpha + \mu + n \f$
        muonicalpha_neutron,  //!< \f$ (\alpha)_\mu + n \f$
        size_
    };

    // Construct from shared and state data
    inline CELER_FUNCTION
    DTMucfInteractor(NativeCRef<DTMixMucfData> const& data,
                     Channel channel,
                     StackAllocator<Secondary>& allocate);

    // Sample an interaction with the given RNG
    template<class Engine>
    inline CELER_FUNCTION Interaction operator()(Engine& rng);

  private:
    // Shared constant physics properties
    NativeCRef<DTMixMucfData> const& data_;
    // Selected fusion channel
    Channel channel_{Channel::size_};
    // Allocate space for secondary particles
    StackAllocator<Secondary>& allocate_;

    // Number of secondaries per channel
    EnumArray<Channel, size_type> num_secondaries_{
        3,  // alpha_muon_neutron
        2  // muonicalpha_neutron
    };

    // Total energy generated by the dt fusion reaction
    inline CELER_FUNCTION units::MevEnergy total_fusion_energy() const
    {
        return units::MevEnergy{17.6};
    }

    // Outgoing neutron kinetic energy
    inline CELER_FUNCTION units::MevEnergy neutron_kinetic_energy() const
    {
        return units::MevEnergy{14.1};
    }

    // Calculate momentum magnitude from energy and mass
    inline CELER_FUNCTION real_type calc_momentum(units::MevEnergy energy,
                                                  units::MevMass mass) const;
};

//---------------------------------------------------------------------------//
// INLINE DEFINITIONS
//---------------------------------------------------------------------------//
/*!
 * Construct with shared data and channel selection.
 */
CELER_FUNCTION
DTMucfInteractor::DTMucfInteractor(NativeCRef<DTMixMucfData> const& data,
                                   Channel const channel,
                                   StackAllocator<Secondary>& allocate)
    : data_(data), channel_(channel), allocate_(allocate)
{
    CELER_EXPECT(data_);
    CELER_EXPECT(channel_ < Channel::size_);
}

//---------------------------------------------------------------------------//
/*!
 * Sample a dt muonic molecule fusion.
 *
 * \note Since secondaries come from an at rest interaction, their final state
 * is a simple combination of random direction + momentum conservation.
 */
template<class Engine>
CELER_FUNCTION Interaction DTMucfInteractor::operator()(Engine& rng)
{
    // Allocate space for the final fusion channel
    Secondary* secondaries = allocate_(num_secondaries_[channel_]);
    if (secondaries == nullptr)
    {
        // Failed to allocate space for secondaries
        return Interaction::from_failure();
    }

    size_type const neutron_idx{0};  // Both channels
    size_type const muon_idx{1}, alpha_idx{2};  // Channel::alpha_muon_neutron
    size_type const muonicalpha_idx{1};  // Channel::muonicalpha_neutron

    IsotropicDistribution sample_isotropic;
    NonuniformGridCalculator sample_muon_energy(data_.muon_energy_cdf,
                                                data_.reals);

    // Neutron is the same on both cases: 14.1 MeV with random direction
    secondaries[neutron_idx].particle_id = data_.particle_ids.neutron;
    secondaries[neutron_idx].energy = this->neutron_kinetic_energy();
    secondaries[neutron_idx].direction = sample_isotropic(rng);

    switch (channel_)
    {
        case Channel::alpha_muon_neutron: {
            // Muon: Final state sampled from CDF
            secondaries[muon_idx].particle_id = data_.particle_ids.mu_minus;
            secondaries[muon_idx].direction = sample_isotropic(rng);
            secondaries[muon_idx].energy = units::MevEnergy{
                sample_muon_energy(generate_canonical(rng))};

            // Alpha: Final state calculated via energy/momentum conservation

            // E_alpha = E_total - E_neutron - E_muon
            auto const alpha_energy = this->total_fusion_energy()
                                      - secondaries[neutron_idx].energy
                                      - secondaries[muon_idx].energy;
            // p_alpha = - (p_neutron + p_muon)
            auto const neutron_momentum_mag = this->calc_momentum(
                secondaries[neutron_idx].energy, data_.particle_masses.neutron);
            auto const muon_momentum_mag = this->calc_momentum(
                secondaries[muon_idx].energy, data_.particle_masses.mu_minus);
            auto const inv_alpha_momentum_mag
                = real_type{1}
                  / this->calc_momentum(alpha_energy,
                                        data_.particle_masses.alpha);

            Real3 alpha_dir;
            for (auto i : range(3))
            {
                alpha_dir[i] = -(secondaries[neutron_idx].direction[i]
                                     * neutron_momentum_mag
                                 + secondaries[muon_idx].direction[i]
                                       * muon_momentum_mag)
                               * inv_alpha_momentum_mag;
            }

            secondaries[alpha_idx].particle_id = data_.particle_ids.alpha;
            secondaries[alpha_idx].direction = alpha_dir;
            secondaries[alpha_idx].energy = alpha_energy;
            break;
        }

        case Channel::muonicalpha_neutron: {
            // Muonic alpha: Equal and opposite momentum to neutron
            secondaries[muonicalpha_idx].particle_id
                = data_.particle_ids.muonic_alpha;
            secondaries[muonicalpha_idx].energy
                = secondaries[neutron_idx].energy;
            for (auto i : range(3))
            {
                secondaries[muonicalpha_idx].direction[i]
                    = -secondaries[neutron_idx].direction[i];
            }
            break;
        }

        default:
            CELER_ASSERT_UNREACHABLE();
    }

    // Kill muon primary and generate fusion secondaries
    Interaction result = Interaction::from_absorption();
    result.secondaries = {secondaries, num_secondaries_[channel_]};
    return result;
}

//---------------------------------------------------------------------------//
/*!
 * Calculate momentum magnitude from particle energy and mass via
 * \f$ p = \sqrt{K^2 + 2mK} \f$
 */
CELER_FUNCTION real_type DTMucfInteractor::calc_momentum(
    units::MevEnergy energy, units::MevMass mass) const

{
    return std::sqrt(ipow<2>(value_as<units::MevEnergy>(energy))
                     + 2 * value_as<units::MevMass>(mass)
                           * value_as<units::MevEnergy>(energy));
}

//---------------------------------------------------------------------------//
}  // namespace celeritas
