//------------------------------- -*- C++ -*- -------------------------------//
// Copyright Celeritas contributors: see top-level COPYRIGHT file for details
// SPDX-License-Identifier: (Apache-2.0 OR MIT)
//---------------------------------------------------------------------------//
//! \file celeritas/io/OpticalDistributionReader.hh
//---------------------------------------------------------------------------//
#pragma once

#include <fstream>
#include <string>

#include "corecel/Macros.hh"
#include "celeritas/optical/gen/GeneratorData.hh"

namespace celeritas
{
//---------------------------------------------------------------------------//
/*!
 * Read optical distribution data from JSON.
 *
 * This reads file generated by \c OpticalDistributionWriter.
 */
class OpticalDistributionReader
{
  public:
    //!@{
    //! \name Type aliases
    using VecDistribution = std::vector<optical::GeneratorDistributionData>;
    //!@}

    // Construct with filename
    explicit OpticalDistributionReader(std::string const& filename);

    //! Prevent copying and moving
    CELER_DELETE_COPY_MOVE(OpticalDistributionReader);
    ~OpticalDistributionReader() = default;

    // Read distribution data from the JSON file
    VecDistribution operator()();

  private:
    std::ifstream infile_;
};

//---------------------------------------------------------------------------//
}  // namespace celeritas
