#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build with a spack-based toolchain.
#
# NOTE: the 'tidy' and 'asan' special cases live in the `build-spack-extra.yml`
# workflow (and `codecov` is in `build-codecov`), since their post-build steps
# diverge significantly from the rest of the matrix.
#-----------------------------------------------------------------------------#

name: build-spack
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-spack-${{github.event.number || github.ref_name}}
  cancel-in-progress: true

jobs:
  spack:
    name: >-
      ${{format(
        '{0}{1}-g4@{2}',
        matrix.special && format('{0}-', matrix.special) || '',
        matrix.geometry,
        matrix.geant
      )}}
    strategy:
      fail-fast: false
      matrix:
        geometry: ["vecgeom"]
        geant: ["10.5"]
    runs-on: ubuntu-24.04
    steps:
      - name: Sleep 1 minute
        run: |
          sleep 60

# vim: set nowrap tw=100:
