#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build directly on the GitHub runner with caching
#-----------------------------------------------------------------------------#

name: build-fast
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

env:
  CELER_VERSION_STRING: >-
    ${{
       github.event.pull_request
       && format('-pr.{0}', github.event.pull_request.number)
       || format('-{0}', github.ref_name)
     }}

jobs:
  linux:
    name: "${{matrix.runner}}-${{matrix.compiler}}-${{matrix.version}}${{matrix.cxxstd && format('-c++{0}', matrix.cxxstd) || ''}}"
    strategy:
      matrix:
        include:
          - runner: jammy
            compiler: gcc
            version: 12
          - runner: jammy
            compiler: clang
            version: 15
            cxxstd: 20
          - runner: noble
            compiler: gcc
            version: 14
          - runner: noble
            compiler: clang
            version: 18
            cxxstd: 20
          - runner: resolute
            compiler: gcc
            version: 15
          - runner: resolute
            compiler: clang
            version: 22
          - runner: resolute-arm
            compiler: gcc
            version: 15
          - runner: resolute-arm
            compiler: clang
            version: 22
    env:
      CELER_JOB_NAME: "${{matrix.runner}}-${{matrix.compiler}}-${{matrix.version}}${{matrix.cxxstd && format('-c++{0}', matrix.cxxstd) || ''}}"
      CELER_CMAKE_PRESET: fast
      CC: ${{matrix.compiler}}-${{matrix.version}}
      CXX: ${{matrix.compiler == 'gcc' && 'g++' || 'clang++'}}-${{matrix.version}}
    runs-on: >-
      ${{  matrix.runner == 'jammy' && 'ubuntu-22.04'
        || matrix.runner == 'noble' && 'ubuntu-24.04'
        || matrix.runner == 'noble-arm' && 'ubuntu-24.04-arm'
        || matrix.runner == 'resolute' && 'ubuntu-26.04'
        || matrix.runner == 'resolute-arm' && 'ubuntu-26.04-arm'
      }}
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7

      ### ENVIRONMENT ###

      - name: Install dependencies
        run: |
          sudo apt-get -q -y update
          sudo apt-get -q -y install \
            ccache \
            nlohmann-json3-dev libgtest-dev libhepmc3-dev libpng-dev \
            ${{matrix.compiler}}-${{matrix.version}} \
            ${{matrix.compiler == 'gcc' && format('g++-{0}', matrix.version) || ''}}
          echo "Installed toolchain:"
          ld --version | head -1
          $CC --version | head -1
          $CXX --version | head -1

      - name: Configure Celeritas
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: ci-ubuntu-github.json
          extra-args: >-
            ${{matrix.cxxstd && format('-DCMAKE_CXX_STANDARD={0}', matrix.cxxstd) || ''}}
          version-string: ${{env.CELER_VERSION_STRING}}

      - name: Build
        id: build
        uses: ./.github/actions/ccache-build
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          name: fast-${{env.CELER_JOB_NAME}}
          ccache-max-size: 200Mi

      - name: Test
        id: test
        uses: ./.github/actions/run-ctest
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          split-app: true
          name: fast-${{env.CELER_JOB_NAME}}

      - name: Install
        if: ${{!cancelled() && steps.build.outputs.build-outcome == 'success'}}
        uses: ./.github/actions/install-and-check

  windows:
    defaults:
      run:
        shell: pwsh
    env:
      CELER_CMAKE_PRESET: fast
      CELER_JOB_NAME: windows
    runs-on: windows-latest
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          choco install ninja ccache
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure Celeritas
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: ci-windows-github.json
          version-string: ${{env.CELER_VERSION_STRING}}
      - name: Build
        id: build
        uses: ./.github/actions/ccache-build
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          name: fast-windows
          ccache-max-size: 200Mi

      - name: Test
        id: test
        uses: ./.github/actions/run-ctest
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          split-app: true
          name: fast-${{env.CELER_JOB_NAME}}

      - name: Install
        if: ${{!cancelled() && steps.build.outputs.build-outcome == 'success'}}
        uses: ./.github/actions/install-and-check

# vim: set nowrap tw=100:
