#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build directly on the GitHub runner with caching
#-----------------------------------------------------------------------------#

name: build-fast
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-fast-${{github.event.number || github.ref_name}}
  cancel-in-progress: true

env:
  CELER_CMAKE_PRESET: fast
  CELER_VERSION_STRING: >-
    ${{
       github.event.pull_request
       && format('-pr.{0}', github.event.pull_request.number)
       || format('-{0}', github.ref_name)
     }}

jobs:
  linux:
    name: >-
      ${{format(
        '{0}-{1}-{2}-c++{3}',
        matrix.runner      ==  'ubuntu-22.04'     && 'jammy'
          || matrix.runner ==  'ubuntu-24.04'     && 'noble'
          || matrix.runner ==  'ubuntu-24.04-arm' && 'noble-arm'
          || matrix.runner ==  'ubuntu-26.04'     && 'resolute'
          || matrix.runner ==  'ubuntu-26.04-arm' && 'resolute-arm',
        matrix.compiler[0],
        matrix.compiler[1],
        matrix.cxxstd || 20
      )}}
    strategy:
      matrix:
        # NOTE: keep synced with top-level README.md
        include:
          - runner: ubuntu-22.04
            compiler: [gcc, 12]
            cxxstd: 17
    runs-on: ${{matrix.runner}}
    steps:
      - name: Sleep 1 minute
        run: |
          sleep 60

# vim: set nowrap tw=100:
