#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build directly on the GitHub runner with caching
#
# NOTE: the 'tidy', 'codecov', and 'asan' special cases live in build-spack-{X}.yml
# since their post-build steps diverge significantly from the rest of the matrix.
#-----------------------------------------------------------------------------#

name: build-spack
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  spack:
    name: >-
      ${{format('{0}{1}{2}{3}{4}',
                matrix.special,
                matrix.special && '-' || '',
                matrix.geometry,
                matrix.geant && '-g4@' || '',
                matrix.geant)}}
    strategy:
      fail-fast: false
      matrix:
        build_type: ["reldeb"]
        geometry: ["vecgeom"]
        special: [""]
        geant: ["10.5", "10.6", "10.7", "11.0", "11.1", "11.2", "11.3"]
        include:
          - build_type: "reldeb"
            geometry: "orange"
            special: "minimal"
            geant: ""
          - build_type: "reldeb"
            geometry: "orange"
            special: "float"
            geant: "11.3"
          - build_type: "ndebug"
            geometry: "orange"
            special: "static"
            geant: "11.3"
          - build_type: "reldeb"
            geometry: "vecgeom"
            special: "clhep"
            geant: "11.3"
          - build_type: "reldeb"
            geometry: "vecgeom2"
            special: ""
            geant: "11.3"
          - build_type: "reldeb"
            geometry: "geant4"
            special: ""
            geant: "11.3"
    env:
      CELER_CMAKE_PRESET: >-
        ${{format('{0}-{1}{2}{3}',
                  matrix.build_type,
                  matrix.geometry,
                  matrix.special && '-' || '',
                  matrix.special)}}
      CC: "clang-18"
      CXX: "clang++-18"
      CXXSTD: ${{(matrix.geant == '10.5' || matrix.geant == '10.6')
        && 17 || 20}}
    runs-on: ubuntu-24.04
    continue-on-error: false
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7
        with:
          fetch-depth: 383
          fetch-tags: true # to get version information

      - name: Set up Spack environment
        uses: ./.github/actions/spack-setup
        with:
          geometry: ${{matrix.geometry}}
          geant: ${{matrix.geant}}
          cxxstd: ${{env.CXXSTD}}
          add-root: >-
            ${{(matrix.special != 'minimal'
                && matrix.special != 'static'
                && env.CXXSTD == '20')
               && 'true' || 'false'}}
      - name: Verify Geant4 environment override
        if: ${{matrix.geant == '11.0'}}
        run: |
          # Test overriding of Geant4 environment variables
          . ${SPACK_VIEW}/rc
          test -n "${G4LEDATA}"

      ### BUILD ###

      - name: Configure Celeritas
        id: configure
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: "ci-ubuntu-github.json"

      - name: Build all
        id: build
        uses: ./.github/actions/ccache-build
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          name: ${{env.CELER_CMAKE_PRESET}}-${{matrix.geant}}
          ccache-max-size: ${{matrix.build_type == 'reldeb' && '500' || '300'}}Mi

      ### TEST ###

      - name: Regenerate ROOT test data
        if: >-
          ${{
            matrix.geant == '11.3'
            && matrix.special != 'minimal'
            && matrix.special != 'static'
          }}
        working-directory: build
        run: |
          ninja -v -k0 update-root-test-data
      - name: Run tests
        id: test
        if: ${{matrix.special != 'static'}}
        uses: ./.github/actions/run-ctest
        with:
          split-app: true
          name: spack-${{env.CELER_CMAKE_PRESET}}-${{matrix.geant}}
          strict: ${{matrix.geant == '11.3' && matrix.geometry != 'vecgeom2'}}
          filter-unit: >-
            ${{
              matrix.special == 'static' && 'none'
              || (matrix.geant && fromJSON(matrix.geant) < 11) && '^accel/'
             }}
      - name: Test basic downstream compilation against build dir
        if: >-
          ${{
            !cancelled()
            && steps.build.outputs.build-outcome == 'success'
          }}
        env:
          CELER_DISABLE_G4_EXAMPLES: 1 # Only test minimal example for this one
        run: |
          . ${SPACK_VIEW}/rc
          CELER_INSTALL_DIR=${PWD}/build ./scripts/ci/test-examples.sh

      ### INSTALL ###

      - name: Install
        id: install
        if: ${{!cancelled() && steps.build.outputs.build-outcome == 'success'}}
        uses: ./.github/actions/install-and-check
        with:
          binaries: orange-update celer-geo celer-export-geant celer-sim celer-g4
      - name: Build and run examples
        env:
          CELER_DISABLE_G4_EXAMPLES: ${{(!matrix.geant) && '1' || ''}}
        if: >-
          ${{
            steps.install.outcome == 'success'
          }}
        run: |
          . ${SPACK_VIEW}/rc
          export G4VERSION_NUMBER=$(echo "${{matrix.geant}}" | awk '{printf "%.0f", $1 * 100}')
          ./scripts/ci/test-examples.sh

# vim: set nowrap tw=100:
