#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build directly on the GitHub runner with caching
#
# NOTE: the 'tidy' and 'asan' special cases live in the `build-spack-extra.yml`
# workflow (and `codecov` is in `build-codecov`), since their post-build steps
# diverge significantly from the rest of the matrix.
#-----------------------------------------------------------------------------#

name: build-spack
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-spack-${{github.event.number || github.ref_name}}
  cancel-in-progress: true

jobs:
  spack:
    name: >-
      ${{format(
        '{0}{1}-g4@{2}',
        matrix.special && format('{0}-', matrix.special) || '',
        matrix.geometry,
        matrix.geant
      )}}
    strategy:
      fail-fast: false
      matrix:
        geometry: ["vecgeom"]
        geant: ["10.5", "10.6", "10.7", "11.0", "11.1", "11.2", "11.3"]
        include:
          - geometry: "orange"
            special: "float"
            geant: "11.3"
          - geometry: "orange"
            special: "static"
            geant: "11.3"
          - geometry: "vecgeom"
            special: "clhep"
            geant: "11.3"
          - geometry: "vecgeom2"
            geant: "11.3"
          - geometry: "geant4"
            geant: "11.3"
    env:
      CELER_CMAKE_PRESET: >-
        ${{format(
          '{0}{1}',
          matrix.geometry,
          matrix.special && format('-{0}', matrix.special) || ''
        )}}
      CELER_RUN_NAME: >-
        ${{format(
          'spack-{0}{1}-g4@{2}',
          matrix.special && format('{0}-', matrix.special) || '',
          matrix.geometry,
          matrix.geant
        )}}
      CC: "clang-18"
      CXX: "clang++-18"
      CXXSTD: ${{(matrix.geant == '10.5' || matrix.geant == '10.6') && 17 || 20}}
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7
        with:
          fetch-tags: true # to get version information

      - name: Set up Spack environment
        uses: ./.github/actions/setup-spack
        with:
          cxxstd: ${{env.CXXSTD}}
          push-buildcache: ${{github.event_name != 'pull_request'}}
          add: >-
            ${{(matrix.special != 'static'
                && env.CXXSTD == '20')
               && 'root' || ''
            }}
            ${{format('geant4@{0}', matrix.geant) || ''}}
            ${{matrix.geometry == 'vecgeom' && 'vecgeom@1.2.11'
               || matrix.geometry == 'vecgeom2' && 'vecgeom@2.0.0-rc.7'
               || ''
            }}
            ${{(matrix.geometry == 'vecgeom'
                || matrix.geometry == 'vecgeom2')
               && 'g4vg' || ''
            }}

      ### BUILD ###

      - name: Configure Celeritas
        id: configure
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: "ci-ubuntu-github.json"

      - name: Build all
        id: build
        uses: ./.github/actions/build-cached
        with:
          name: ${{env.CELER_RUN_NAME}}
          preset: spack
          ccache-max-size: "320Mi"

      ### TEST ###

      - name: Regenerate ROOT test data
        if: >-
          ${{
            matrix.geant == '11.3'
            && matrix.special != 'static'
          }}
        working-directory: build
        run: |
          ninja -v -k0 update-root-test-data
      - name: Run tests
        id: test
        if: ${{matrix.special != 'static'}}
        uses: ./.github/actions/run-ctest
        with:
          name: ${{env.CELER_RUN_NAME}}
          preset: spack
          split-app: true
          strict: ${{matrix.geant == '11.3' && matrix.geometry != 'vecgeom2'}}
          filter-unit: >-
            ${{
              matrix.special == 'static' && 'none'
              || fromJSON(matrix.geant) < 11 && '^accel/'
             }}
      - name: Test basic downstream compilation against build dir
        if: ${{ !cancelled() && steps.build.outputs.build-outcome == 'success' }}
        env:
          CELER_DISABLE_G4_EXAMPLES: 1 # Only test minimal example for this one
        run: |
          CELER_INSTALL_DIR=${PWD}/build ./scripts/ci/test-examples.sh

      ### INSTALL ###

      - name: Install
        id: install
        if: ${{ !cancelled() && steps.build.outputs.build-outcome == 'success' }}
        uses: ./.github/actions/install-and-check
        with:
          binaries: orange-update celer-geo celer-export-geant celer-sim celer-g4
      - name: Build and run examples
        env:
          CELER_DISABLE_G4_EXAMPLES: "0"
        if: ${{ !cancelled() && steps.install.outcome == 'success' }}
        run: |
          export G4VERSION_NUMBER=$(echo "${{matrix.geant}}" | awk '{printf "%.0f", $1 * 100}')
          "${{github.workspace}}/scripts/ci/test-examples.sh"

# vim: set nowrap tw=100:
