#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Run clang-tidy on changed files (or, on a schedule, the whole build) using Spack.
#-----------------------------------------------------------------------------#

name: build-spack-tidy
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  tidy:
    name: tidy-vecgeom
    env:
      CELER_CMAKE_PRESET: reldeb-vecgeom-tidy
      CLANG_TIDY: "clang-tidy-18"
      CC: "clang-18"
      CXX: "clang++-18"
      CXXSTD: 20
    runs-on: ubuntu-24.04
    continue-on-error: false
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7
        with:
          fetch-depth: 383
          fetch-tags: true # to get version information

      - name: Set up Spack environment
        uses: ./.github/actions/spack-setup
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          geometry: vecgeom
          geant: "11.2"
          cxxstd: ${{env.CXXSTD}}
          add-root: "true"
          fetch-depth: "0" # need full history to diff against the base branch

      - name: Configure Celeritas
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: "ci-ubuntu-github.json"

      - name: Build changed files with clang-tidy
        id: tidy
        run: |
          ./scripts/ci/clag-tidy-changed.sh "${{format('{0}', github.base_ref || 'develop')}}"

# vim: set nowrap tw=100:
