#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build unusual spack jobs (not just app/unit tests)
#-----------------------------------------------------------------------------#

name: build-spack-extra
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-spack-extra-${{github.event.number || github.ref_name}}
  cancel-in-progress: true

env:
  CC: "clang-18"
  CXX: "clang++-18"
  CXXSTD: 20

jobs:
  asan:
    name: orange-asanlite
    env:
      CELER_CMAKE_PRESET: orange-asanlite
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7
        with:
          fetch-tags: true # to get version information
      - name: Set up Spack environment
        uses: ./.github/actions/setup-spack
        with:
          cxxstd: ${{env.CXXSTD}}
      - name: Configure Celeritas
        id: configure
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: "ci-ubuntu-github.json"
      - name: Build all
        id: build
        uses: ./.github/actions/build-cached
        with:
          name: spack-${{env.CELER_CMAKE_PRESET}}
          preset: spack
          ccache-max-size: 512Mi
      - name: Run tests
        id: test
        uses: ./.github/actions/run-ctest
        with:
          name: spack-${{env.CELER_CMAKE_PRESET}}
          preset: spack
          split-app: true
          strict: false

  tidy:
    name: tidy-vecgeom
    env:
      CELER_CMAKE_PRESET: vecgeom-tidy
      CLANG_TIDY: "clang-tidy-18"
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7
        with:
          fetch-tags: true # to get version information
      - name: Set up Spack environment
        uses: ./.github/actions/setup-spack
        with:
          add: "geant4@11.2 vecgeom@1.2.11:1 g4vg"
          cxxstd: ${{env.CXXSTD}}
      - name: Configure Celeritas
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: "ci-ubuntu-github.json"
      - name: Build changed files with clang-tidy
        if: ${{github.event_name == 'pull_request'}}
        run: |
          "${{github.workspace}}/scripts/ci/clang-tidy-changed.sh" \
            "origin" \
            "${{ github.event.pull_request.base.sha }}"
      # NOTE: this was not previously used on develop so will be disabled
      - name: Build all files with clang-tidy
        if: ${{github.event_name != 'pull_request'}}
        run: cmake --build --preset=spack

# vim: set nowrap tw=100:
