#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build directly on the GitHub runner with caching
#-----------------------------------------------------------------------------#

name: build-fast
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-fast-${{github.event.number || github.ref_name}}
  cancel-in-progress: true

env:
  CELER_CMAKE_PRESET: fast
  CELER_VERSION_STRING: >-
    ${{
       github.event.pull_request
       && format('-pr.{0}', github.event.pull_request.number)
       || format('-{0}', github.ref_name)
     }}

jobs:
  linux:
    name: >-
      ${{format(
        '{0}-{1}-{2}-c++{3}',
        matrix.runner      ==  'ubuntu-22.04'     && 'jammy'
          || matrix.runner ==  'ubuntu-24.04'     && 'noble'
          || matrix.runner ==  'ubuntu-24.04-arm' && 'noble-arm'
          || matrix.runner ==  'ubuntu-26.04'     && 'resolute'
          || matrix.runner ==  'ubuntu-26.04-arm' && 'resolute-arm',
        matrix.compiler[0],
        matrix.compiler[1],
        matrix.cxxstd || 17
      )}}
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04
            compiler: [gcc, 12]
          - runner: ubuntu-22.04
            compiler: [clang, 15]
            cxxstd: 20
          - runner: ubuntu-24.04
            compiler: [gcc, 14]
          - runner: ubuntu-24.04
            compiler: [clang, 18]
            cxxstd: 20
          - runner: ubuntu-26.04
            compiler: [gcc, 15]
          - runner: ubuntu-26.04
            compiler: [clang, 22]
            cxxstd: 20
          - runner: ubuntu-26.04-arm
            compiler: [gcc, 15]
          - runner: ubuntu-26.04-arm
            compiler: [clang, 22]
    env:
      CELER_JOB_NAME: >-
        ${{format(
          '{0}-{1}-{2}-c++{3}',
          matrix.runner,
          matrix.compiler[0],
          matrix.compiler[1],
          matrix.cxxstd || 17
        )}}
      CC: ${{format('{0}-{1}', matrix.compiler[0], matrix.compiler[1])}}
      CXX: >-
        ${{format(
          '{0}-{1}',
          (matrix.compiler[0] == 'gcc' && 'g++'
           || matrix.compiler[0] == 'clang' && 'clang++'),
          matrix.compiler[1]
        )}}
      CXXSTD: ${{matrix.cxxstd || 17}}
    runs-on: ${{matrix.runner}}
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7

      ### ENVIRONMENT ###

      - name: Install dependencies
        run: |
          sudo apt-get -q -y update
          sudo apt-get -q -y install \
            ccache \
            nlohmann-json3-dev libgtest-dev libhepmc3-dev libpng-dev \
            ${{format('{0}-{1}', matrix.compiler[0], matrix.compiler[1])}} \
            ${{matrix.compiler[0] == 'gcc' && format('g++-{0}', matrix.compiler[1]) || ''}}
          echo "Installed toolchain:"
          ld --version | head -1
          $CC --version | head -1
          $CXX --version | head -1

      - name: Configure Celeritas
        uses: $/.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: ci-ubuntu-github.json
          version-string: ${{env.CELER_VERSION_STRING}}

      - name: Build
        id: build
        uses: $/.github/actions/build-cached
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          name: fast-${{env.CELER_JOB_NAME}}
          ccache-max-size: 192Mi

      - name: Test
        id: test
        uses: $/.github/actions/run-ctest
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          split-app: true
          name: fast-${{env.CELER_JOB_NAME}}

      - name: Install
        if: ${{ !cancelled() && steps.build.outputs.build-outcome == 'success' }}
        uses: $/.github/actions/install-and-check

  windows:
    defaults:
      run:
        shell: pwsh
    env:
      CELER_JOB_NAME: windows
    runs-on: windows-2025
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          choco install ninja ccache
      - name: Set up MSVC
        uses: TheMrMilchmann/setup-msvc-dev@368ef7d1ee4d1171b31d4a7f67f4d954f903f5a9 # v4.1.0, 22 July 2026
        with:
          arch: x64

      - name: Configure Celeritas
        uses: $/.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: ci-windows-github.json
          version-string: ${{env.CELER_VERSION_STRING}}
      - name: Build
        id: build
        uses: $/.github/actions/build-cached
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          name: fast-windows
          ccache-max-size: 192Mi

      - name: Test
        id: test
        uses: $/.github/actions/run-ctest
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          split-app: true
          name: fast-${{env.CELER_JOB_NAME}}

      - name: Install
        if: ${{ !cancelled() && steps.build.outputs.build-outcome == 'success' }}
        uses: $/.github/actions/install-and-check

# vim: set nowrap tw=100:
