#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build using CUDA/ROCm docker images
#-----------------------------------------------------------------------------#

name: build-docker-codecov
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

concurrency:
  group: build-docker-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  # TODO: since we don't build on GPU systems with cuda/rocm docker,
  # none of the tests actually run on device
  docker:
    name: >-
      ${{format('codecov-{0}-{1}-{2}',
                matrix.geometry,
                matrix.buildtype,
                matrix.image)}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - buildtype: "ndebug"
            geometry: "vecgeom"
            geant: "11.3"
            image: "rocky-cuda"

    env:
      CELER_DISABLE_DEVICE: 1 # REQUIRED for GHA runners
      CELER_CMAKE_PRESET: >-
        ${{format('{0}-{1}-codecov',
                matrix.buildtype,
                matrix.geometry)}}
    runs-on: ubuntu-24.04
    container:
      image: >-
        docker.io/celeritas/${{
             matrix.image == 'rocky-cuda' && 'ci-rocky-cuda12:2024-12-29'
        }}
    steps:
      - name: Set up environment
        run: |
          . /etc/profile
          echo "/opt/view/bin" >> $GITHUB_PATH
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}" >> $GITHUB_ENV
      # NOTE: checkout must occur *after* setting up environment for git tags to work
      # NOTE: depth must be enough to include the previous tag
      - name: Check out Celeritas
        uses: actions/checkout@v7
        with:
          fetch-depth: 383
          fetch-tags: true

      - name: Trust checked-out repo
        run: |
          git config --global --add safe.directory ${PWD}

      ### BUILD ###

      - name: Configure Celeritas
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: ci-${{matrix.image}}.json

      - name: Build Celeritas
        id: build
        working-directory: build
        run: |
          echo "::group::Build verbosely"
          ninja -v -k0
          echo "::endgroup::"

      ### TEST ###

      - name: Test Celeritas
        id: test
        uses: ./.github/actions/run-ctest
        with:
          name: ${{matrix.image}}-${{env.CELER_CMAKE_PRESET}}
      - name: Generate and upload coverage report
        uses: ./.github/actions/generate-coverage
        if: >-
          ${{
            !cancelled()
            && steps.test.outcome == 'success'
          }}
        with:
          codecov_token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true

# vim: set nowrap tw=100:
