#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build unusual spack jobs (not just app/unit tests)
#-----------------------------------------------------------------------------#

name: build-spack-extra
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-spack-extra-${{github.event.number || github.ref_name}}
  cancel-in-progress: true

env:
  CC: "clang-18"
  CXX: "clang++-18"
  CXXSTD: 20

jobs:
  asan:
    name: orange-asanlite
    env:
      CELER_CMAKE_PRESET: orange-asanlite
    runs-on: ubuntu-24.04
    steps:
      - name: Sleep 1 minute
        run: |
          sleep 60

# vim: set nowrap tw=100:
