#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build Celeritas with minimal dependencies using only local packages
#-----------------------------------------------------------------------------#

name: build-ultralite
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: build-ultralite-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  linux:
    name: ultralite-ubuntu
    env:
      CC: "clang-18"
      CXX: "clang++-18"
      LLVM_COV: "llvm-cov-18"
      GCOV: "${{github.workspace}}/scripts/ci/llvm-gcov.sh"
      CMAKE_PRESET: ultralite-codecov
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v4

      ### ENVIRONMENT ###

      - name: Install dependencies
        run: |
          sudo apt-get -q -y update
          sudo apt-get -q -y install \
            ccache nlohmann-json3-dev libpng-dev

      ### CONFIGURE ###

      - name: Configure Celeritas
        run: |
          ln -fs scripts/cmake-presets/ci-ubuntu-github.json CMakeUserPresets.json
          cmake --version
          cmake --preset=${CMAKE_PRESET} --log-level=VERBOSE \
            -DCeleritas_GIT_DESCRIBE="${{github.event.pull_request
              && format(';-pr.{0};;;', github.event.pull_request.number)
              || format(';-{0};;;', github.ref_name)}}"

      ### BUILD ###

      - name: Build
        id: build
        working-directory: build
        run: |
          ninja

      ### TEST ###

      - name: Run tests
        id: test
        run: |
          ctest --preset=ultralite

      - name: Generate and upload coverage report
        uses: ./.github/actions/generate-coverage
        if: ${{!cancelled() && steps.test.outcome == 'success'}}
        with:
          codecov_token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          gcov_executable: ${{env.GCOV}}
