#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build and upload code coverage
#-----------------------------------------------------------------------------#

name: build-codecov
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      # The codecov token is only used when pushing to protected branches
      # (main/develop), since secrets are *not* passed from the main
      # celeritas project to the PR run on the fork.
      CODECOV_TOKEN:
        required: false

concurrency:
  group: build-codecov-${{github.event.number || github.ref_name}}
  cancel-in-progress: true

jobs:
  spack:
    name: spack-vecgeom
    runs-on: ubuntu-24.04
    steps:
      - name: Sleep 2 minutes
        run: |
          sleep 120

# vim: set nowrap tw=100:
