#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build and run only integration regression tests.
# - Run automatically as part of PRs, push-to-develop, cron cache reset
# - Run manually via workflow_dispatch (button in https://github.com/celeritas-project/celeritas/actions)
# - Regression files for failed tests (or *all* tests if workflow_dispatch) will be uploaded as an artifact
#-----------------------------------------------------------------------------#

name: build-regression
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: build-regression-${{github.event.number || github.ref_name}}
  cancel-in-progress: true

jobs:
  accel:
    env:
      CELER_CMAKE_PRESET: "orange-regression"
      CELER_RUN_NAME: "regression-orange-g4@11.3"
      CC: "clang-18"
      CXX: "clang++-18"
      CXXSTD: 20
    runs-on: ubuntu-24.04
    steps:
      - name: Sleep 1 minute
        run: |
          sleep 60

# vim: set nowrap tw=100:
