name: Check dd4hep integration

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - feature-dd4hep-integration-plugin

concurrency:
  group: build-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  check-dd4hep-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cvmfs-contrib/github-action-cvmfs@v5
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "eic_xl:nightly"
        network_types: "none"
        run: |
          eic-info
          cmake -DCELERITAS_USE_DD4hep=ON -DCMAKE_INSTALL_PREFIX=install -S . -B build
          cmake --build build -j 8
          cmake --install build
          export LD_LIBRARY_PATH=$PWD/install/lib:${LD_LIBRARY_PATH}

          # Run with Celeritas enabled
          ddsim --action.run DDcelerRunAction --compactFile=$PWD/example/ddceler/SiD_ConstantField.xml --steering $PWD/example/ddceler/steeringFile.py -N 20 -G --gun.particle e- --gun.etaMax 2 --gun.etaMin 1 --gun.energy 5*GeV --gun.distribution uniform --outputFile output_celeritas.root --outputConfig.forceDD4HEP  --action.tracker "Geant4TrackerAction" --action.trackerSDTypes "tracker" --action.calorimeter "Geant4CalorimeterAction" --action.calorimeterSDTypes "calorimeter"

          # Run with Celeritas disabled (Geant4 only)
          CELER_DISABLE=1 ddsim --action.run DDcelerRunAction --compactFile=$PWD/example/ddceler/SiD_ConstantField.xml --steering $PWD/example/ddceler/steeringFile.py -N 20 -G --gun.particle e- --gun.etaMax 2 --gun.etaMin 1 --gun.energy 5*GeV --gun.distribution uniform --outputFile output_geant4.root --outputConfig.forceDD4HEP  --action.tracker "Geant4TrackerAction" --action.trackerSDTypes "tracker" --action.calorimeter "Geant4CalorimeterAction" --action.calorimeterSDTypes "calorimeter"

          # Compare benchmarks and generate plots
          root -l -b -q '$PWD/example/ddceler/compare_benchmarks.cc("output_geant4.root", "output_celeritas.root")'

    - name: Upload comparison plots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: comparison-plots
        path: "*.png"
