name: ci

on:
  push:
    branches:
      - develop
      - backports/**
  pull_request:
    branches:
      - develop
      - backports/**
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  # TODO: skip tests if only `scripts` has changed (dorny/paths-filter)?
  # TODO: clang format 
  #  clang-format-check:
  #    name: Check formatting
  #    runs-on: ubuntu-latest
  #    steps:
  #    - name: Check out repository
  #      uses: actions/checkout@v3
  #    - name: Run clang-format style check for C/C++/CUDA
  #      uses: jidicula/clang-format-action@v4.11.0
  #      with:
  #        clang-format-version: '17'
  build:
    name: CI
    strategy:
      matrix:
        image: ['ubuntu-cuda', 'centos-rocm']
        buildtype: ['debug', 'ndebug']
        geometry: ['orange', 'vecgeom']
        special: [null]
        exclude:
          - image: 'centos-rocm'
            geometry: 'vecgeom'
        include:
          - image: 'centos-rocm'
            buildtype: 'asan'
            geometry: 'orange'
          - image: 'centos-rocm'
            buildtype: 'debug'
            geometry: 'orange'
            special: 'float'
          - image: 'centos-rocm'
            buildtype: 'reldeb'
            geometry: 'geant4'
          - image: 'ubuntu-cuda'
            buildtype: 'reldeb'
            geometry: 'vecgeom'
    env:
      ASAN_OPTIONS: "detect_leaks=0"
        #      CCACHE_DIR: "${{github.workspace}}/.ccache"
        #      CCACHE_MAXSIZE: "10G"
      CELER_TEST_STRICT: 1
      CELER_DISABLE_DEVICE: 1 # IMPORTANT
      CMAKE_PRESET: >-
        ${{matrix.buildtype}}-${{matrix.geometry}}${{matrix.special && '-' || ''}}${{matrix.special}}
    runs-on: ubuntu-latest
    container:
      image: >-
        docker.io/celeritas/${{
             matrix.image == 'ubuntu-cuda' && 'ci-jammy-cuda11:2023-08-02'
          || matrix.image == 'centos-rocm' && 'ci-centos7-rocm5:2022-12-14.2'
          || null
        }}
      # TODO: don't use a 'root' user
      # See https://github.com/actions/checkout/issues/956
      options: --user root
    steps:
      # TODO: use ccache?
      #      - name: Cache ccache
      #        uses: actions/cache@v2
      #        with:
      #          path: ${{ env.CCACHE_DIR }}
      #          key: ccache-${{ matrix.distro }}-${{github.run_id}}
      #          restore-keys: ccache-${{ matrix.distro }}
      #      - name: Zero ccache stats
      #        run: |
      #          ccache -z
      - name: Set up environment
        run: |
          . /etc/profile
          echo "/opt/view/bin" >> $GITHUB_PATH
          echo "CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}" >> $GITHUB_ENV
      # NOTE: checkout must occur *after* setting up environment for git tags to work
      # NOTE: checkout v4 fails: https://github.com/actions/checkout/issues/1487
      # TODO: shallow copy + git describe with cmake git version?
      - name: Check out Celeritas
        uses: actions/checkout@v3
        with:
          fetch-depth: 255
          fetch-tags: true
      - name: Configure Celeritas
        run: |
          git config --global --add safe.directory ${PWD}
          ln -fs scripts/cmake-presets/ci-${{matrix.image}}.json CMakeUserPresets.json
          cmake --preset=${CMAKE_PRESET}
      - name: Build Celeritas
        run: |
          cmake --build --preset=${CMAKE_PRESET}
      - name: Test Celeritas
        working-directory: build
        run: |
          ctest --timeout 180 --output-on-failure \
            --test-output-size-passed=65536 --test-output-size-failed=1048576
      - name: Install Celeritas
        run: |
          . /etc/profile
          cmake --install build
      - name: Check installation
        run: |
          for exe in orange-update celer-export-geant celer-dump-data \
            celer-sim celer-g4; do
            test -x "install/bin/${exe}"
          done
          ./install/bin/celer-sim --version
      - name: Build examples
        # TODO: asan needs -fsanitize=address
        # TODO: rocm+ndebug fails to propagate HIP library link
        # TODO: logger gets initialized in SimpleOffload::Build before run manager
        if: >-
          ${{ matrix.buildtype != 'asan'
           && !(matrix.image == 'centos-rocm' && matrix.buildtype == 'ndebug')
           && !(matrix.geometry == 'vecgeom' && matrix.buildtype != 'ndebug')
          }}
        run: |
          if [ "${{matrix.geometry}}" = "vecgeom" ]; then
            # TODO: vecgeom is loosey goosey about symbols whereas Ubuntu is strict
            export LDFLAGS=-Wl,--no-as-needed
          fi
          ./scripts/ci/test-examples.sh
          #      - name: Show ccache stats
          #        run: |
          #          ccache -s
# vim: set nowrap tw=100:
