name: clear-cache

on:
  workflow_dispatch:
  workflow_call:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear ccache
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Getting action cache")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key.startsWith("ccache-")) {
                console.log("Deleting cache entry", cache)
                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
              }
            }
