#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Clear cache and rebuild it every week
#-----------------------------------------------------------------------------#

name: cron_weekly

on:
  schedule:
    - cron: "33 06 * * 0" # Sunday at 6:33 am UTC

jobs:
  clear-cache:
    if: ${{ vars.CELER_CI }}
    uses: ./.github/workflows/clear-cache.yml
  build-ultralite:
    needs: [clear-cache]
    uses: ./.github/workflows/build-ultralite.yml
  build-fast:
    needs: [clear-cache]
    uses: ./.github/workflows/build-fast.yml
  build-spack:
    needs: [clear-cache]
    uses: ./.github/workflows/build-spack.yml
  build-spack-extra:
    needs: [clear-cache]
    uses: ./.github/workflows/build-spack-extra.yml
  build-regression:
    needs: [clear-cache]
    uses: ./.github/workflows/build-regression.yml
  build-codecov:
    needs: [clear-cache]
    uses: ./.github/workflows/build-codecov.yml
    secrets: inherit

# vim: set nowrap tw=100:
