#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Clear cache and rebuild it every week
#-----------------------------------------------------------------------------#

name: cron_weekly

on:
  schedule:
    - cron: "33 06 * * 0" # Sunday at 6:33 am UTC

jobs:
  clear-cache:
    uses: ./.github/workflows/clear-cache.yml
  build-ultralite:
    if: github.repository == 'celeritas-project/celeritas'
    needs: [clear-cache]
    uses: ./.github/workflows/build-ultralite.yml
  build-fast:
    if: github.repository == 'celeritas-project/celeritas'
    needs: [clear-cache]
    uses: ./.github/workflows/build-fast.yml
  build-spack:
    if: github.repository == 'celeritas-project/celeritas'
    needs: [clear-cache]
    uses: ./.github/workflows/build-spack.yml
  build-spack-extra:
    if: github.repository == 'celeritas-project/celeritas'
    needs: [clear-cache]
    uses: ./.github/workflows/build-spack-extra.yml
  build-codecov:
    if: github.repository == 'celeritas-project/celeritas'
    needs: [clear-cache]
    uses: ./.github/workflows/build-codecov.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

# vim: set nowrap tw=100:
