name: deploy-pages
on:
  push:
    branches:
      - develop
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  doc:
    uses: ./.github/workflows/doc.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [doc]
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Check out Celeritas doc base
        uses: actions/checkout@v4
        with:
          ref: doc/gh-pages-base
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Download doc and user artifacts
        uses: actions/download-artifact@v4
      - name: Rename artifacts
        run: |
          mv doc-dev dev
          mv doc-user user
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

# vim: set nowrap tw=100:
