name: doc
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: doc-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

env:
  celer_upload_doc:  >-
    ${{  github.ref_name == 'develop'
      || contains(github.ref_name, 'backports/')
      || contains(github.head_ref, 'release-')
      || contains(github.head_ref, 'doc-')
    }}

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get -y update
            sudo apt-get -y install \
                cmake graphviz ninja-build doxygen gcc
      - name: Check out Celeritas
        uses: actions/checkout@v4
        with:
          fetch-depth: 255
          fetch-tags: true
      - name: Configure celeritas
        # Turn warnings into errors only for PRs
        # Disable expensive graphs for PRs also
        run: |
          mkdir build && cd build
          cmake \
            -DCELERITAS_BUILD_DOCS=ON \
            -DCELERITAS_DOXYGEN_BUILD_TESTS=ON \
            ${{ github.workflow == 'pr'
             && '-DDOXYGEN_WARN_AS_ERROR="YES" -DDOXYGEN_HAVE_DOT="NO"'
             || ''}} \
            -GNinja \
            ..
      - name: Build documentation
        working-directory: build
        run: |
          ninja doxygen
      - name: Upload pages artifacts
        if: ${{env.celer_upload_doc}}
        id: upload-pages-user
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/doc/doxygen-html
  user:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get -y update
            sudo apt-get -y install \
                cmake graphviz ninja-build doxygen gcc
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Check out Celeritas
        uses: actions/checkout@v4
        with:
          fetch-depth: 255
          fetch-tags: true
      - name: Install Python packages
        run: |
            pip install --upgrade pip
            pip install -r scripts/requirements.txt
      - name: Configure celeritas
        run: |
          mkdir build && cd build
          cmake \
            -DCELERITAS_BUILD_DOCS=ON \
            -DDOXYGEN_HAVE_DOT="NO" \
            -DDOXYGEN_WARN_AS_ERROR="YES" \
            -GNinja ..
      - name: Build user documentation
        working-directory: build
        run: |
          ninja doc
      - name: Upload pages artifacts
        if: ${{env.celer_upload_doc}}
        id: upload-pages-user
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/doc/html
#TODO: deploy with actions/deploy-pages@v2 ?

# vim: set nowrap tw=100:
