#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Build and upload documentation
#-----------------------------------------------------------------------------#

name: doc
on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: doc-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

env:
  # Turn warnings into errors only for PRs, and disable expensive graphs for PRs also
  CELER_CMAKE_PRESET: ${{ format('doc-{0}', github.workflow == 'pull_request' && '-check' || '-publish' }}
  CELER_UPLOAD_DOC: >-
    ${{  github.ref_name == 'develop'
      || contains(github.ref_name, 'backports/')
      || contains(github.head_ref, 'release-')
      || contains(github.event.pull_request.labels.*.name, 'documentation')
    }}

jobs:
  dev:
    env:
      CELER_TARGET: doxygen
      CELER_UPLOAD_DIR: build/doc/doxygen-html
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v6
        with:
          fetch-depth: 383
          fetch-tags: true
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
              cmake graphviz ninja-build doxygen nlohmann-json3-dev

      - name: Configure Celeritas
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: ci-ubuntu-github.json

      - name: Build documentation
        run: |
          cmake --build --preset=${CELER_CMAKE_PRESET} --target ${CELER_TARGET}
          find ${CELER_UPLOAD_DIR} -name '*.md5' -exec rm {} +

      - name: Upload artifacts
        if: ${{env.CELER_UPLOAD_DOC}}
        uses: actions/upload-artifact@v7
        with:
          path: ${{env.CELER_UPLOAD_DIR}}
          name: doc-dev
          if-no-files-found: error
          overwrite: true
          retention-days: 1 # developer docs can be large

  user:
    runs-on: ubuntu-24.04
    env:
      CELER_TARGET: doc
      CELER_UPLOAD_DIR: build/doc/html
    steps:
      - name: Check out Celeritas
        uses: actions/checkout@v6
        with:
          fetch-depth: 383
          fetch-tags: true
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
              cmake graphviz ninja-build doxygen nlohmann-json3-dev
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install -r scripts/ci/doc-requirements.txt

      - name: Configure Celeritas
        uses: ./.github/actions/configure
        with:
          preset: ${{env.CELER_CMAKE_PRESET}}
          presets-file: ci-ubuntu-github.json
      - name: Build documentation
        run: |
          cmake --build --preset=${CELER_CMAKE_PRESET} --target ${CELER_TARGET}
          find ${CELER_UPLOAD_DIR} -name '*.md5' -exec rm {} +

      - name: Upload artifacts
        if: ${{env.CELER_UPLOAD_DOC}}
        uses: actions/upload-artifact@v7
        with:
          path: ${{env.CELER_UPLOAD_DIR}}
          name: doc-user
          if-no-files-found: error
          overwrite: true
          retention-days: 7 # user docs might need review


# vim: set nowrap tw=100:
