name: doc
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: doc-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  user:
    name: user
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get -y update
            sudo apt-get -y install \
                cmake graphviz ninja-build doxygen gcc
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Check out Celeritas
        uses: actions/checkout@v4
        with:
          fetch-depth: 255
          fetch-tags: true
      - name: Install Python packages
        run: |
            pip install --upgrade pip
            pip install -r scripts/requirements.txt
      - name: Configure celeritas
        run: |
          mkdir build && cd build
          cmake -DCELERITAS_BUILD_DOCS=ON -GNinja ..
      - name: Build user documentation
        working-directory: build
        run: |
          ninja doc
      - name: Build developer documentation
        working-directory: build
        run: |
          ninja doxygen
      - name: Upload user artifacts
        id: upload-pages-user
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/doc/html
      - name: Upload developer artifacts
        id: upload-pages-dev
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/doc/doxygen
#TODO: deploy with actions/deploy-pages@v2 ?

# vim: set nowrap tw=100:
