#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Run a series of progressively expensive checks on each pull request
#-----------------------------------------------------------------------------#

name: pull_request
# Run name renders as `#{PR number}: {PR title}`
run-name: >-
  #${{github.event.number}}: ${{github.event.pull_request.title}}

on:
  pull_request:
    branches:
      - develop
      - backports/**
    paths-ignore:
      - "**.rst"
      - "**.md"
      - "scripts"
      - ".jenkins"
      - "!scripts/cmake-presets/ci*"
      - "!scripts/ci"
      - "!scripts/build.sh"

# Only allow one PR action per PR, and cancel old ones when a new one (e.g. new commit)
# is triggered
concurrency:
  group: pr-${{github.event.number}}
  cancel-in-progress: true

jobs:
  metadata:
    name: "Save job metadata"
    runs-on: ubuntu-24.04
    steps:
      # Event file is needed for pull_request_completed.report-tests
      - name: Upload event file
        id: upload
        uses: actions/upload-artifact@v7
        with:
          name: event-file
          path: ${{github.event_path}}
  build-fast:
    uses: ./.github/workflows/build-fast.yml
  build-ultralite:
    uses: ./.github/workflows/build-ultralite.yml
  build-docs:
    uses: ./.github/workflows/build-docs.yml
  all-prechecks:
    needs:
      - build-fast
      - build-ultralite
      - build-docs
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        run: "true"
  build-spack:
    needs: [all-prechecks]
    uses: ./.github/workflows/build-spack.yml

  # Since docker builds aren't cached and are large, don't run on draft
  # Also avoid coverage checks until ready (those are also expensive)
  build-spack-extra:
    if: ${{github.event.pull_request.draft == false}}
    needs: [all-prechecks]
    uses: ./.github/workflows/build-spack-extra.yml
  build-docker:
    if: ${{github.event.pull_request.draft == false}}
    needs: [all-prechecks]
    uses: ./.github/workflows/build-docker.yml
  build-codecov:
    if: ${{github.event.pull_request.draft == false}}
    needs: [all-prechecks]
    uses: ./.github/workflows/build-codecov.yml

  # Specifying a dependent job allows us to select a single "requires" check in the project GitHub settings
  all:
    if: ${{!cancelled()}}
    needs:
      - build-spack
      - build-spack-extra
      - build-docker
      - build-codecov
    runs-on: ubuntu-24.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@v1.3.0 # immutable, 21 Aug 2026
        with:
          jobs: ${{toJSON(needs)}}

# vim: set nowrap tw=100:
