name: pull_request
run-name: >-
  ${{github.event.pull_request.title}}
  (#${{github.event.number}})

on:
  pull_request:
    branches:
      - develop
      - backports/**
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'scripts'
      - '.jenkins'
      - '!scripts/cmake-presets/ci*'
      - '!scripts/ci'
      - '!scripts/build.sh'

concurrency:
  group: pr-${{github.ref}}-${{github.event.number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  build-docker:
    uses: ./.github/workflows/build-docker.yml

# vim: set nowrap tw=100:
