name: pull_request
run-name: >-
  ${{github.event.pull_request.title}}
  (#${{github.event.number}})

on:
  pull_request:
    branches:
      - develop
      - backports/**
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'scripts'
      - '.jenkins'
      - '!scripts/cmake-presets/ci*'
      - '!scripts/ci'
      - '!scripts/build.sh'

concurrency:
  group: pr-${{github.ref}}-${{github.event.number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  build-ultralite:
    uses: ./.github/workflows/build-ultralite.yml
  all-prechecks:
    needs: [build-ultralite]
    runs-on: ubuntu-latest
    steps:
    - name: Success
      run: "true"
  build-docker:
    uses: ./.github/workflows/build-docker.yml

  # Specifying a dependent job allows us to select a single "requires" check in the project GitHub settings
  all:
    if: ${{always()}}
    needs:
    - build-docker
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{toJSON(needs)}}

# vim: set nowrap tw=100:
