name: pull_request_completed

# NOTE: this workflow runs on the *develop* branch of the main repository
# after an incoming pull request is run. Changes to this script *will not*
# affect a PR and must first be tested on the develop branch of a fork.
on:
  workflow_run:
    workflows: ["pull_request"]
    types:
      - completed

permissions:
  checks: write
  pull-requests: write

jobs:
  report-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Download and Extract Artifacts
      uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d # v6
      with:
        name: "(event-file|test-results-.*)"
        name_is_regexp: true
        run_id: ${{github.event.workflow_run.id}}
        path: artifacts
    - name: Publish PR comment
      uses: EnricoMi/publish-unit-test-result-action@82082dac68ad6a19d980f8ce817e108b9f496c2a # v2.17.1
      if: always()
      with:
        check_name: "Test summary"
        commit: ${{github.event.workflow_run.head_sha}}
        event_file: artifacts/event-file/event.json
        event_name: ${{github.event.workflow_run.event}}
        files: "artifacts/**/*.xml"
    - name: Publish comments on source code
      uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4.3.1
      if: always()
      with:
        commit: ${{github.event.workflow_run.head_sha}}
        report_paths: "artifacts/**/*.xml"

# vim: set nowrap tw=100:
