#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Run a series of progressively expensive checks on each pull request
#-----------------------------------------------------------------------------#

name: pull_request
# Run name renders as `#{PR number}: {PR title}`
run-name: >-
  #${{github.event.number}}: ${{github.event.pull_request.title}}

on:
  pull_request:
    branches:
      - develop
      - backports/**
    paths-ignore:
      - "**.rst"
      - "**.md"
      - "scripts"
      - ".jenkins"
      - "!scripts/cmake-presets/ci*"
      - "!scripts/ci"
      - "!scripts/build.sh"

# Only allow one PR action per PR, and cancel old ones when a new one (e.g. new commit)
# is triggered
concurrency:
  group: pr-${{github.event.number}}
  cancel-in-progress: true

jobs:
  build-spack:
    uses: ./.github/workflows/build-spack.yml

# vim: set nowrap tw=100:
