name: pull_request
run-name: >-
  ${{github.event.pull_request.title}}
  (#${{github.event.number}})

on:
  pull_request:
    branches:
      - develop
      - backports/**
    paths-ignore:
      - '**.rst'
      - '**.md'
      - 'scripts'
      - '.jenkins'
      - '!scripts/cmake-presets/ci*'
      - '!scripts/ci'
      - '!scripts/build.sh'

concurrency:
  group: pr-${{github.ref}}-${{github.event.number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  metadata:
    name: "Save job metadata"
    runs-on: ubuntu-latest
    steps:
    # Event file is needed for EnricoMi/publish-unit-test-result-action
    - name: Upload event file
      uses: actions/upload-artifact@v4
      with:
        name: event-file
        path: ${{github.event_path}}
  build-fast:
    uses: ./.github/workflows/build-fast.yml
  build-ultralite:
    uses: ./.github/workflows/build-ultralite.yml
  doc:
    uses: ./.github/workflows/doc.yml
  all-prechecks:
    needs: [build-fast, build-ultralite, doc]
    runs-on: ubuntu-latest
    steps:
    - name: Success
      run: "true"
  build-docker:
    # Since docker builds aren't cached and are large, don't run on draft
    if: ${{github.event.pull_request.draft == false}}
    needs: [all-prechecks]
    uses: ./.github/workflows/build-docker.yml
  build-spack:
    needs: [all-prechecks]
    uses: ./.github/workflows/build-spack.yml

  # Specifying a dependent job allows us to select a single "requires" check in the project GitHub settings
  all:
    if: ${{always()}}
    needs:
    - build-docker
    - build-spack
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{toJSON(needs)}}

# vim: set nowrap tw=100:
