#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Run tests on push to develop/backport branches.
#-----------------------------------------------------------------------------#

name: push

on:
  push:
    branches:
      - develop
      - backports/**

concurrency:
  group: push-${{github.ref}}-${{github.run_number}}-${{github.workflow}}
  cancel-in-progress: false

jobs:
  build-ultralite:
    uses: ./.github/workflows/build-ultralite.yml
  build-fast:
    uses: ./.github/workflows/build-fast.yml
  build-docker:
    uses: ./.github/workflows/build-docker.yml
  build-spack:
    uses: ./.github/workflows/build-spack.yml
  build-spack-asan:
    uses: ./.github/workflows/build-spack-asan.yml
  build-spack-tidy:
    uses: ./.github/workflows/build-spack-tidy.yml
  build-docker-codecov:
    if: github.repository_owner == 'celeritas-project'
    uses: ./.github/workflows/build-docker-codecov.yml
    secrets: inherit
  build-spack-codecov:
    if: github.repository_owner == 'celeritas-project'
    uses: ./.github/workflows/build-spack-codecov.yml
    secrets: inherit
  all:
    needs:
      [
        build-fast,
        build-docker,
        build-spack,
        build-spack-asan,
        build-spack-tidy,
        build-spack-codecov,
      ]
    runs-on: ubuntu-24.04
    steps:
      - name: Success
        run: "true"

# vim: set nowrap tw=100:
