#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Run tests on push to develop/backport branches.
#-----------------------------------------------------------------------------#

name: push
# Run name renders as `{branch}: {head commit subject}`
run-name: >-
  ${{github.ref_name}}: ${{github.event.head_commit.message}}

on:
  push:
    branches:
      - develop
      - backports/**

concurrency:
  group: push-${{github.ref_name}}-${{github.run_number}}
  cancel-in-progress: true

jobs:
  check-ci-vars:
    # See https://github.com/celeritas-project/celeritas/settings/variables/actions
    # or  https://github.com/{user}/celeritas/settings/variables/actions
    # This should be set to a "truthy" value for celeritas-project and any fork that
    # wants to do regular testing.
    name: Check CELER_CI variable
    if: ${{ vars.CELER_CI }}
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: |
          echo "Running on repository ${{ github.repository }}"
  build-ultralite:
    needs: [check-ci-vars]
    uses: ./.github/workflows/build-ultralite.yml
  build-fast:
    needs: [check-ci-vars]
    uses: ./.github/workflows/build-fast.yml
  build-docker:
    needs: [check-ci-vars]
    uses: ./.github/workflows/build-docker.yml
  build-spack:
    needs: [check-ci-vars]
    uses: ./.github/workflows/build-spack.yml
  build-spack-extra:
    needs: [check-ci-vars]
    uses: ./.github/workflows/build-spack-extra.yml
  build-regression:
    needs: [check-ci-vars]
    uses: ./.github/workflows/build-regression.yml
  build-codecov:
    needs: [check-ci-vars]
    uses: ./.github/workflows/build-codecov.yml
    secrets: inherit

# vim: set nowrap tw=100:
